### ISSUE TITLE
Access rights on API description

### ISSUE THREAD

**Issue by lup-** [Changecoins/http-client#1]
Trying to access API description, mentioned in README

https://changecoins.postman.co/collections/13288095-9742a431-c6f9-4d76-9a8e-8bc6a55dd72c?version=latest&workspace=987b5dd4-f368-427b-8959-3705d9b33f53

But no luck:( Access denied:( Can you, please, fix access rights?

**Comment by Changecoins** [comment]
Fixed, use this link https://documenter.getpostman.com/view/13288095/TVsvfS6E
